name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci_lint_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/golangci-lint.yml@690755db19239c07610e3afff1fe904a73de62c4
    with:
      timeout: 20m
