name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci_lint_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/golangci-lint.yml@3d2d3eca2bf7d7ded958b41b6408664b85e76d12
    with:
      timeout: 20m
