name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci_lint_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/golangci-lint.yml@d43b861891f5d98605bf0ae543cc75430e7c4854
    with:
      timeout: 20m
