name: Release Steampipe Anywhere Components

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (must be prefixed with 'v')"
        required: true

permissions:
  contents: write

jobs:
  anywhere_publish_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/steampipe-anywhere-aws.yml@3d2d3eca2bf7d7ded958b41b6408664b85e76d12
