name: Release Steampipe Anywhere Components

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (must be prefixed with 'v')"
        required: true

permissions:
  contents: write

jobs:
  anywhere_publish_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/steampipe-anywhere-aws.yml@d43b861891f5d98605bf0ae543cc75430e7c4854
