name: Sync Labels
on:
  schedule:
    - cron: "30 22 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync_labels_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/sync-labels.yml@d43b861891f5d98605bf0ae543cc75430e7c4854
